---
image: node:latest

cache:
  paths:
    - node_modules/

build:
  stage: test
  script:
    - npm install
    - echo Tests still TODO

package:
  stage: deploy
  script:
    - npm install
    - mkdir -p public/js public/css
    - npm run build
    - npm uninstall --save-prod
    - npm pack
  artifacts:
    paths:
      - './*.tgz'
